/**
 * Generated from contracts/story-presentation/motion-capabilities.json.
 * Do not edit this file by hand. Run `pnpm contracts:generate`.
 */

export const MOTION_CAPABILITY_REGISTRY_VERSION = '1.0.0' as const
export const MOTION_CAPABILITY_REGISTRY_HASH = '2e260a90f65c5ad81b91b8ed60e0423b8f6bf709c6387f84471a1aaa25f6b348' as const
export const MOTION_CAPABILITIES = [
  {
    "id": "pod-css-keyframes.v1",
    "executor": "pod_css",
    "triggers": [
      "idle",
      "scene-enter"
    ],
    "parameterSchemaRef": "harvested-css-keyframes.v1",
    "sourceFragmentPolicy": "side-effect-free-css-only",
    "reducedMotion": "disable",
    "focusPolicy": "not-interactive",
    "evidenceRequirements": [
      "animation-metadata",
      "computed-style",
      "reduced-motion"
    ]
  },
  {
    "id": "pod-css-transition.v1",
    "executor": "pod_css",
    "triggers": [
      "hover",
      "focus"
    ],
    "parameterSchemaRef": "harvested-css-transition.v1",
    "sourceFragmentPolicy": "side-effect-free-css-only",
    "reducedMotion": "disable",
    "focusPolicy": "preserve",
    "evidenceRequirements": [
      "computed-style",
      "target-geometry",
      "reduced-motion",
      "focus-state"
    ]
  },
  {
    "id": "story-reveal-on-enter.v1",
    "executor": "storytime",
    "triggers": [
      "scene-enter"
    ],
    "parameterSchemaRef": "modes/motion.schema.json#/$defs/revealParameters",
    "sourceFragmentPolicy": "none",
    "reducedMotion": "final-state",
    "focusPolicy": "preserve",
    "evidenceRequirements": [
      "animation-metadata",
      "computed-style",
      "target-geometry",
      "reduced-motion",
      "focus-state"
    ]
  },
  {
    "id": "story-scroll-progress-transform.v1",
    "executor": "storytime",
    "triggers": [
      "scroll-progress"
    ],
    "parameterSchemaRef": "modes/motion.schema.json#/$defs/scrollTransformParameters",
    "sourceFragmentPolicy": "none",
    "reducedMotion": "final-state",
    "focusPolicy": "not-interactive",
    "evidenceRequirements": [
      "computed-style",
      "normalized-progress",
      "target-geometry",
      "reduced-motion"
    ]
  },
  {
    "id": "story-count-up-on-enter.v1",
    "executor": "storytime",
    "triggers": [
      "scene-enter"
    ],
    "parameterSchemaRef": "modes/motion.schema.json#/$defs/countUpParameters",
    "sourceFragmentPolicy": "none",
    "reducedMotion": "final-state",
    "focusPolicy": "not-interactive",
    "evidenceRequirements": [
      "computed-style",
      "animation-metadata",
      "reduced-motion"
    ]
  },
  {
    "id": "story-progress-reveal.v1",
    "executor": "storytime",
    "triggers": [
      "scene-enter",
      "scroll-progress"
    ],
    "parameterSchemaRef": "modes/motion.schema.json#/$defs/progressRevealParameters",
    "sourceFragmentPolicy": "none",
    "reducedMotion": "final-state",
    "focusPolicy": "not-interactive",
    "evidenceRequirements": [
      "computed-style",
      "normalized-progress",
      "target-geometry",
      "reduced-motion"
    ]
  }
] as const
