/**
 * Generated from contracts/story-presentation/*.schema.json.
 * Do not edit this file by hand. Run `pnpm contracts:generate`.
 */

export type StoryFlowMode = 'scrolly' | 'timed-path'
export type StoryControlsMode = 'default' | 'minimal' | 'pill' | 'arrows'
export type StoryJumpAlign = 'center' | 'start' | 'end'
export type StoryScrollTarget = 'step' | 'card'
export type StoryChapterNavChromeMode = 'default' | 'floating-rail'
export type StoryChapterNavBrandMode = 'text' | 'image' | 'mark' | 'none'
export type StoryScrollHintMode = 'default' | 'corner'
export type StoryActivationMode = 'step-exit' | 'card-center' | 'card-exit-next'
export type StoryIntroExitTarget = 'default' | 'step-target' | 'scrolly-start'
export type StoryVisualTransitionMode = 'fade' | 'cross-reveal'

/**
 * Versioned presentation metadata for an Autumn story.
 */
export interface GeneratedStoryPresentation {
  flowMode?: StoryFlowMode
  navMode?: string
  brandLabel?: string
  navBrandLabel?: string
  navAriaLabel?: string
  chapters?: GeneratedStoryChapter[]
  controls?: StoryControlsPresentation
  chapterNav?: StoryChapterNavPresentation
  scrollHint?: StoryScrollHintPresentation
  scroll?: StoryScrollPresentation
  visualTransitionMode?: StoryVisualTransitionMode
  [k: string]: unknown
}
export interface GeneratedStoryChapter {
  id: string
  label: string
  shortLabel?: string
  sceneKeys: string[]
  children?: GeneratedStoryChapter[]
  [k: string]: unknown
}
export interface StoryControlsPresentation {
  variant?: 'default' | 'minimal' | 'we2'
  controlMode?: StoryControlsMode
  keyboard?: boolean
  showShare?: boolean
  showProgress?: boolean
  showVideoControls?: boolean
  hideOnMobileBelow?: number
  autoHideOnMobile?: boolean
  bottomOffsetPx?: number
  responsiveBottomOffsetPx?: StoryResponsiveNumberRule[]
  jumpAlign?: StoryJumpAlign
  responsiveJumpAlign?: StoryResponsiveJumpAlignRule[]
  jumpEndOffsetPx?: number
  responsiveJumpEndOffsetPx?: StoryResponsiveNumberRule[]
  jumpTarget?: StoryScrollTarget
  mobileCta?: StoryChapterNavCtaPresentation | null
  reaction?: StoryControlsReactionPresentation | null
  [k: string]: unknown
}
export interface StoryResponsiveNumberRule {
  minWidth?: number
  maxWidth?: number
  value: number
  [k: string]: unknown
}
export interface StoryResponsiveJumpAlignRule {
  minWidth?: number
  maxWidth?: number
  value: StoryJumpAlign
  [k: string]: unknown
}
export interface StoryChapterNavCtaPresentation {
  url?: string
  label?: string
  suffix?: string
  ariaLabel?: string
  target?: '_blank' | '_self'
  rel?: string
  downloadFilename?: string
  trackLabel?: string
  trackModifier?: string
  [k: string]: unknown
}
export interface StoryControlsReactionPresentation {
  enabled?: boolean
  label?: string
  count?: number
  modifier?: string
  [k: string]: unknown
}
export interface StoryChapterNavPresentation {
  variant?: 'default' | 'we2'
  chromeMode?: StoryChapterNavChromeMode
  brandMode?: StoryChapterNavBrandMode
  showToggle?: boolean
  inactiveLabel?: string
  inactiveBehavior?: 'none' | 'first-chapter'
  brand?: StoryChapterNavBrandPresentation
  cta?: StoryChapterNavCtaPresentation | null
  darkSceneKeys?: string[]
  jumpAlign?: StoryJumpAlign
  responsiveJumpAlign?: StoryResponsiveJumpAlignRule[]
  jumpEndOffsetPx?: number
  responsiveJumpEndOffsetPx?: StoryResponsiveNumberRule[]
  jumpTarget?: StoryScrollTarget
  [k: string]: unknown
}
export interface StoryChapterNavBrandPresentation {
  variant?: 'text' | 'image' | 'mark' | 'we2-mark'
  mode?: StoryChapterNavBrandMode
  label?: string
  logoUrl?: string
  mobileLogoUrl?: string
  sceneKeys?: string[]
  [k: string]: unknown
}
export interface StoryScrollHintPresentation {
  enabled?: boolean
  variant?: 'default' | 'we2'
  mode?: StoryScrollHintMode
  label?: string
  sceneKeys?: string[]
  fontFamily?: string
  bottomOffsetPx?: number
  responsiveBottomOffsetPx?: StoryResponsiveNumberRule[]
  [k: string]: unknown
}
export interface StoryScrollPresentation {
  jumpTarget?: StoryScrollTarget
  activationMode?: StoryActivationMode
  activationAnchor?: number
  activationHysteresisPx?: number
  introExitTarget?: StoryIntroExitTarget
  introExitDurationMs?: number
  introReturnDurationMs?: number
  disableSnap?: boolean
  stepMinHeight?: string
  viewportStackStepMinHeight?: string
  [k: string]: unknown
}

export type StoryMotionBinding =
  | StoryRevealOnEnterBinding
  | StoryScrollProgressTransformBinding
  | StoryCountUpOnEnterBinding
  | StoryProgressRevealBinding
export type StoryMotionTargetKey = string
export type StoryMotionEasing = 'linear' | 'ease' | 'ease-in' | 'ease-out' | 'ease-in-out'

/**
 * Presentation metadata stored on an Autumn story scene.
 */
export interface StoryScenePresentation {
  flow?: 'scrolly' | 'standalone'
  narrativeTreatment?: 'none' | 'single' | 'synchronized'
  layout?: 'split' | 'full'
  cardMode?: 'side-by-side' | 'overlay' | 'viewport-stack' | 'hidden'
  responsiveCardMode?: 'side-by-side' | 'overlay' | 'viewport-stack' | 'hidden'
  responsiveBreakpoint?: number
  cardAlign?: 'left' | 'center' | 'right'
  mobileLeadInDvh?: number
  mobileLeadOutDvh?: number
  mobileCardGapDvh?: number
  mobileMinHeightDvh?: number
  motion?: StorySceneMotionPresentation
  articleSteps?: {
    align?: 'left' | 'center' | 'right'
    desktopOnly?: boolean
    mobileOnly?: boolean
    mobileTopOffsetDvh?: number
    mobileBottomOffsetDvh?: number
    mobileMinHeightDvh?: number
    triggerCenterFraction?: number
    blockIndex?: number
    blockIndexes?: number[]
    [k: string]: unknown
  }[]
  [k: string]: unknown
}
export interface StorySceneMotionPresentation {
  version: '1.0.0'
  registryVersion: '1.0.0' | '1.1.0'
  registryHash: string
  /**
   * @maxItems 64
   */
  bindings: StoryMotionBinding[]
}
export interface StoryRevealOnEnterBinding {
  targetKey: StoryMotionTargetKey
  capabilityId: 'story-reveal-on-enter.v1'
  trigger: 'scene-enter'
  parameters: StoryRevealOnEnterParameters
}
export interface StoryRevealOnEnterParameters {
  axis?: 'x' | 'y' | 'none'
  distancePx?: number
  durationMs?: number
  delayMs?: number
  staggerMs?: number
  easing?: StoryMotionEasing
}
export interface StoryScrollProgressTransformBinding {
  targetKey: StoryMotionTargetKey
  capabilityId: 'story-scroll-progress-transform.v1'
  trigger: 'scroll-progress'
  parameters: StoryScrollProgressTransformParameters
}
export interface StoryScrollProgressTransformParameters {
  axis: 'x' | 'y'
  from: number
  to: number
  unit: 'px' | 'percent'
  opacityFrom?: number
  opacityTo?: number
}
export interface StoryCountUpOnEnterBinding {
  targetKey: StoryMotionTargetKey
  capabilityId: 'story-count-up-on-enter.v1'
  trigger: 'scene-enter'
  parameters: StoryCountUpOnEnterParameters
}
export interface StoryCountUpOnEnterParameters {
  from: number
  to: number
  durationMs?: number
  delayMs?: number
  decimals?: number
  prefix?: string
  suffix?: string
}
export interface StoryProgressRevealBinding {
  targetKey: StoryMotionTargetKey
  capabilityId: 'story-progress-reveal.v1'
  trigger: 'scene-enter' | 'scroll-progress'
  parameters: StoryProgressRevealParameters
}
export interface StoryProgressRevealParameters {
  fromPercent: number
  toPercent: number
  durationMs?: number
  delayMs?: number
  easing?: StoryMotionEasing
}

export const STORY_PRESENTATION_CONTRACT_VERSION = '1.2.0' as const
